theme: jekyll-theme-minimal
markdown: kramdown 

plugins:
  - jekyll-relative-links
  
relative_links:
  exclude:
    - index.md
    - experience.md
    - projects.md

owner:
  bio: "Eat and Drink, enjoy good in my labor"
  email: yuanweipi@gmail.com
  github: yuap94

